[project]
name = "lasr-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sam Dower", email = "samdower@hotmail.co.uk" }
]
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.30.0",
    "ipython>=8.18.1",
    "matplotlib>=3.9.4",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "wandb>=0.21.0",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "src/probe_gen",
]
