[project]
name = "lasr-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sam Dower", email = "samdower@hotmail.co.uk" }
]
requires-python = ">=3.9"
dependencies = [
    "torch>=2.7.1",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"
