from .refusal_dataset import SYSTEM_PROMPT_REFUSAL
from .tinystories_dataset import (
    SYSTEM_PROMPT_LISTS_STORY,
    SYSTEM_PROMPT_METAPHOR_STORY,
    SYSTEM_PROMPT_REFUSAL_STORY,
    SYSTEM_PROMPT_SCIENCE_STORY,
)
from .ultrachat_dataset import (
    SYSTEM_PROMPT_LISTS,
    SYSTEM_PROMPT_METAPHORS,
    SYSTEM_PROMPT_SCIENCE,
)

# Make all imports available for backwards compatibility
__all__ = [
    'SYSTEM_PROMPT_REFUSAL',
    'SYSTEM_PROMPT_LISTS_STORY',
    'SYSTEM_PROMPT_METAPHOR_STORY', 
    'SYSTEM_PROMPT_REFUSAL_STORY',
    'SYSTEM_PROMPT_SCIENCE_STORY',
    'SYSTEM_PROMPT_LISTS',
    'SYSTEM_PROMPT_METAPHORS',
    'SYSTEM_PROMPT_SCIENCE',
]
