experiments:
  - behaviour: sycophancy
    datasources: ["multichoice"]
    generation_methods: ["on_policy", "prompted"]
    off_policy_model: "qwen_7b"
    activations_model: "llama_3b"
    layers: [12]
    train_size: 10
    test_size: 10
    temperature: 0.0